# Pre-testing installs

install:

  - echo "nothing needs to be installed"




# Scripts to be run such as tests

before_script:

  - echo "no tests"




script:

  - docker --version # print the version for logging

  - docker-compose up

  - docker tag udagram-api-feed duonglp97/udagram-api-feed:v1
  - docker tag udagram-api-user duonglp97/udagram-api-user:v1
  - docker tag udagram-frontend duonglp97/udagram-frontend:v1
  - docker tag udagram-reverseproxy duonglp97/udagram-reverseproxy:v1




after_success:

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push duonglp97/udagram-api-feed:v1
  - docker push duonglp97/udagram-api-user:v1
  - docker push duonglp97/udagram-frontend:v1
  - docker push duonglp97/udagram-reverseproxy:v1

